"""THE FIXED-WIDTH READERS (wdb_fw, generated by tools/gen_fw.py): every generated kernel equals the
general reader and the values it packed -- plain bitpack every width 1..32 across chunk edges and a
ragged tail; enc 10 every width 1..16 with run and bitpack blocks mixed and a short last block; enc 19
shelved with blocks of 1 to 16384 distinct values (pointer widths 0..14) and a ragged last block."""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))
sys.path.insert(0, os.path.dirname(__file__))
import numpy as np
import wdb_fw as FW
import wdb_kernels as K
import wdb_encode
import wdb_engine


def _pack_msb(a, B):
    bits = ((a[:, None] >> np.arange(B - 1, -1, -1, dtype=np.int64)) & 1).astype(np.uint8).ravel()
    return np.packbits(bits)


def test_bp0_every_width():
    rng = np.random.default_rng(5)
    for B in range(1, 33):
        n = (1 << 18) * 2 + 13 if B in (1, 7, 27, 32) else 3001
        a = rng.integers(0, 1 << B, n, dtype=np.int64)
        buf = np.concatenate([np.zeros(5, np.uint8), _pack_msb(a, B), np.zeros(8, np.uint8)])
        dt = np.uint8 if B <= 8 else (np.uint16 if B <= 16 else np.uint32)
        got = np.zeros(n, dt); FW.BP0[B](buf, np.int64(5), np.int64(n), got)
        ref = np.zeros(n, dt); K.bp0_decode(buf, 5, B, n, ref)
        assert np.array_equal(got, a.astype(dt)), B
        assert np.array_equal(got, ref), B


def test_bp10_every_width_runs_and_bits_mixed():
    rng = np.random.default_rng(6)
    for B in range(1, 17):
        n = 4096 * 5 + 1234
        a = rng.integers(0, 1 << B, n, dtype=np.int64)
        a[4096:8192] = min(3, (1 << B) - 1)                     # one block of a single run
        pay = bytearray(); dirX = []
        for b in range(0, n, 4096):
            blk = a[b:b + 4096]
            if (b // 4096) % 2 == 1:                            # odd blocks as runs
                st = np.concatenate([[0], np.flatnonzero(np.diff(blk)) + 1]); en = np.concatenate([st[1:], [blk.size]])
                dirX.append((len(pay) << 1) | 1)
                pay += np.array([st.size], np.uint16).tobytes()
                pr = np.empty(2 * st.size, np.uint16); pr[0::2] = en - st; pr[1::2] = blk[st]
                pay += pr.tobytes()
            else:
                dirX.append(len(pay) << 1)
                pay += _pack_msb(blk, B).tobytes()
        buf = np.concatenate([np.zeros(3, np.uint8), np.frombuffer(bytes(pay), np.uint8), np.zeros(8, np.uint8)])
        dirX = np.array(dirX, np.int64)
        dt = np.uint16 if B > 8 else np.uint8
        got = np.zeros(n, dt); FW.BP10[B](buf, dirX, np.int64(3), np.int64(n), got)
        ref = np.zeros(n, dt); K.bp10_decode(buf, dirX, 3, B, n, ref)
        assert np.array_equal(got, a.astype(dt)), B
        assert np.array_equal(got, ref), B


def test_e19s_blocks_every_pointer_width():
    import test_blockdict as TB
    rng = np.random.default_rng(7)
    for bits, R in ((17, 3), (25, 7)):
        BRt = 16384
        parts = []
        for k in (1, 2, 3, 5, 9, 100, 1000, 5000, 16384):      # distinct values per block
            vals = rng.choice(1 << bits, k, replace=False)
            parts.append(vals[rng.integers(0, k, BRt)])
        parts.append(rng.integers(0, 1 << bits, 777))           # a ragged last block
        a = np.concatenate(parts).astype(np.int64); n = a.size
        with TB._shelves(R):
            sec = wdb_encode._e19_candidate(a, bits, float('inf'))
        BR, nb, lb, gw, dc, poff, R_, wb, W, SW, pre, soff, pw, dw = TB._shelved_parts(sec)
        c = {'e19BR': BR, 'e19W': W, 'e19wb': wb, 'e19lb': lb, 'e19gw': gw, 'e19dc': dc, 'e19poff': poff,
             'e19pre': pre, 'e19soff': soff, 'e19SW': SW}
        assert len(set(lb.tolist())) >= 6, lb                   # many widths really exercised
        for on in (True, False):
            wdb_engine._FWR[0] = on
            try:
                out = np.zeros(n, np.int64)
                wdb_engine._e19s_blocks(c, pw, dw, n, 0, nb, out)
                assert np.array_equal(out, a), (bits, R, on)
                out2 = np.zeros(n, np.int64)                    # a sub-range of blocks, as the pipeline slices
                wdb_engine._e19s_blocks(c, pw, dw, n, 2, nb - 1, out2)
                lo, hi = 2 * BR, (nb - 1) * BR
                assert np.array_equal(out2[lo:hi], a[lo:hi]) and not out2[:lo].any(), (bits, R, on)
            finally:
                wdb_engine._FWR[0] = True
