#!/usr/bin/env python3
"""Canonical-corpus scoreboard: join the TPC-H matrix (examples/report.md) and a ClickBench
board JSON (examples/boards/*.json) onto the 37 canonical shapes (docs/crosswalk.md) and emit
one row per shape. Matrix = lineitem 6M warm best-of-5 speedup; clickbench = hits 100M warm
ratio; both are DuckDB / WaveDB (>1 = WaveDB faster).

Usage:
  python bench/canon_table.py [board.json] [--write]
    board.json  ClickBench board (default: examples/boards/clickbench_board_retyped.json)
    --write     also write docs/board.md (otherwise prints to stdout)
"""
import json, re, os, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def parse_matrix(path):
    """report.md per-query rows -> {M#: (speedup, ok)}."""
    mat = {}
    for ln in open(path):
        if not ln.strip().startswith('|'):
            continue
        f = [c.strip() for c in ln.strip().strip('|').split('|')]
        if len(f) < 12 or not f[0].isdigit():
            continue
        m = re.match(r'([\d.]+)x', f[7])
        if m:
            mat[int(f[0])] = (float(m.group(1)), f[11] == 'ok')
    return mat


def parse_board(path):
    """ClickBench board json -> {Q#: (ratio, ok, err)}."""
    return {r['idx']: (r.get('ratio'), r['ok'] is True, r.get('err'))
            for r in json.load(open(path))}


def parse_crosswalk(path):
    """docs/crosswalk.md 'Canonical -> source' table -> [(C, benches, shape, [M#], [Q#])]."""
    rows, sec = [], False
    for ln in open(path):
        if ln.startswith('## Canonical'):
            sec = True; continue
        if sec and ln.startswith('##') and 'Canonical' not in ln:
            break
        if sec and re.match(r'\|\s*C\d\d', ln):
            f = [c.strip() for c in ln.strip().strip('|').split('|')]
            rows.append((f[0], f[1], f[2],
                         [int(x[1:]) for x in re.findall(r'M\d+', f[3])],
                         [int(x[1:]) for x in re.findall(r'Q\d+', f[4])]))
    return rows


def _fmt_m(Ms, mat):
    out = [f"M{m} {mat[m][0]:.1f}x" + ("" if mat[m][1] else "*") for m in Ms if m in mat]
    return ', '.join(out) if out else '—'


def _fmt_q(Qs, cb):
    out = []
    for q in Qs:
        if q not in cb:
            continue
        ratio, ok, err = cb[q]
        if err and ratio is None:
            out.append(f"Q{q} " + ('T/O' if 'TIMEOUT' in str(err) else 'ERR'))
        else:
            out.append(f"Q{q} {ratio:.1f}x" + ("" if ok else "*"))
    return ', '.join(out) if out else '—'


def _verdict(Ms, Qs, mat, cb):
    mwin = any(mat.get(m, (0, False))[1] and mat[m][0] >= 1 for m in Ms)
    qok = [cb[q] for q in Qs if q in cb]
    qwin = any(ok and (r or 0) >= 1 for r, ok, e in qok)
    qany = any(ok for r, ok, e in qok)
    if Ms and Qs:
        return 'WIN both' if (mwin and qwin) else ('WIN partial' if (mwin or qwin) else 'mixed/loss')
    if Ms:
        return 'WIN ours' if mwin else 'loss ours'
    if Qs:
        return 'WIN cb' if qwin else ('ok slow' if qany else 'gap/loss')
    return '—'


def build(board_path):
    mat = parse_matrix(os.path.join(REPO, 'examples', 'report.md'))
    cb = parse_board(board_path)
    rows = parse_crosswalk(os.path.join(REPO, 'docs', 'crosswalk.md'))
    out = []
    out.append('| C | bench | shape | matrix (lineitem 6M) | clickbench (hits 100M) | verdict |')
    out.append('|---|---|---|---|---|---|')
    tally = {}
    for c, benches, shape, Ms, Qs in rows:
        v = _verdict(Ms, Qs, mat, cb)
        tally[v] = tally.get(v, 0) + 1
        out.append(f"| {c} | {benches} | {shape} | {_fmt_m(Ms, mat)} | {_fmt_q(Qs, cb)} | {v} |")
    out.append('')
    out.append('Ratio = DuckDB / WaveDB warm (>1 = WaveDB faster). `*` = ok=False '
               '(tie-only or unverified). ERR / T/O = error or >45s timeout.')
    out.append('')
    out.append('Verdict tally: ' + ', '.join(f"{k} {v}" for k, v in sorted(tally.items())))
    return '\n'.join(out)


def main():
    args = [a for a in sys.argv[1:] if a != '--write']
    board = args[0] if args else os.path.join(REPO, 'examples', 'boards', 'clickbench_board_retyped.json')
    table = build(board)
    if '--write' in sys.argv:
        dst = os.path.join(REPO, 'docs', 'board.md')
        with open(dst, 'w') as fh:
            fh.write('# Canonical-corpus scoreboard\n\n')
            fh.write(f'Generated by `bench/canon_table.py` from `examples/report.md` (TPC-H matrix) '
                     f'and `{os.path.relpath(board, REPO)}` (ClickBench), joined on `docs/crosswalk.md`.\n\n')
            fh.write(table + '\n')
        print(f'wrote {dst}')
    else:
        print(table)


if __name__ == '__main__':
    main()
