"""THE FIXED-WIDTH READERS (Jackson, 2026-09-30: "if it was finetuned for something it might get
slightly faster"). Writes src/wdb_fw.py: one numba kernel per bit width, every shift a constant.
  python tools/gen_fw.py            (then commit both files; never edit wdb_fw.py by hand)
The kernels live in a real file so numba's cache=True keeps them across processes (a cold run would
otherwise recompile). Three families, each measured exact against the general reader:
  bp0_B   plain MSB-first bitpack (enc 0), B = 1..32: 8 values = B bytes.
  bp10_B  enc 10's bitpack blocks (4096 rows, byte-aligned), B = 1..16; run blocks as before.
  e19s_L  enc 19 shelved pointers, L = 1..16: 64 rows = L whole u64 words (blocks start on a word)."""
import os

HEAD = '''"""GENERATED by tools/gen_fw.py -- do not edit. The fixed-width readers: one kernel per bit width."""
import numpy as np
from numba import njit, prange
from wdb_kernels import _e19s_dict, _e19_get

U = np.uint64
'''


def _eight(B, pvar, qvar, ind):
    """8 MSB-first values of B bits from B bytes at buf[pvar..], into out[qvar..qvar+7]"""
    L = [ind + 'y%d = U(buf[%s + %d])' % (j, pvar, j) for j in range(B)]
    for k in range(8):
        s = k * B; f = s >> 3; l = (s + B - 1) >> 3; nby = l - f + 1
        acc = ' | '.join('(y%d << U(%d))' % (f + t, 8 * (nby - 1 - t)) for t in range(nby))
        L.append(ind + 'out[%s + %d] = ((%s) >> U(%d)) & U(%d)' % (qvar, k, acc, 8 * nby - ((s & 7) + B), (1 << B) - 1))
    return L


def bp0(B):
    L = ['', '', '@njit(nogil=True, parallel=True, cache=True)',
         'def bp0_%d(buf, base, N, out):' % B,
         '    CH = 1 << 18                                  # chunks start byte-aligned: 2^18 * B bits',
         '    for cix in prange((N + CH - 1) // CH):',
         '        a = cix * CH',
         '        b = min(N, a + CH)',
         '        ng = (b - a) // 8',
         '        p0 = base + (a * %d) // 8' % B,
         '        for g in range(ng):',
         '            p = p0 + g * %d' % B,
         '            q = a + g * 8']
    L += _eight(B, 'p', 'q', '            ')
    L += ['        for i in range(a + ng * 8, b):',
          '            v = U(0)',
          '            for t in range(%d):' % B,
          '                bb = i * %d + t' % B,
          '                v = (v << U(1)) | ((U(buf[base + (bb >> 3)]) >> U(7 - (bb & 7))) & U(1))',
          '            out[i] = v']
    return L


def bp10(B):
    L = ['', '', '@njit(nogil=True, parallel=True, cache=True)',
         'def bp10_%d(buf, dirX, pay, N, out):' % B,
         '    for b in prange(dirX.size):',
         '        lo = b * 4096',
         '        rows = min(4096, N - lo)',
         '        o = pay + (dirX[b] >> 1)',
         '        if dirX[b] & 1:                               # run block: u16 (count, value) pairs',
         '            nr = np.int64(buf[o]) | (np.int64(buf[o + 1]) << 8)',
         '            p = o + 2',
         '            w = lo',
         '            for r in range(nr):',
         '                cnt = np.int64(buf[p]) | (np.int64(buf[p + 1]) << 8)',
         '                val = np.int64(buf[p + 2]) | (np.int64(buf[p + 3]) << 8)',
         '                p += 4',
         '                for i in range(cnt):',
         '                    out[w] = val',
         '                    w += 1',
         '            continue',
         '        ng = rows // 8',
         '        for g in range(ng):',
         '            p = o + g * %d' % B,
         '            q = lo + g * 8']
    L += _eight(B, 'p', 'q', '            ')
    L += ['        for r in range(ng * 8, rows):',
          '            v = U(0)',
          '            for t in range(%d):' % B,
          '                bb = r * %d + t' % B,
          '                v = (v << U(1)) | ((U(buf[o + (bb >> 3)]) >> U(7 - (bb & 7))) & U(1))',
          '            out[lo + r] = v']
    return L


def e19s(Lw):
    M = (1 << Lw) - 1
    L = ['', '', '@njit(nogil=True, parallel=True, cache=True)',
         'def e19s_%d(pw, dw, BR, N, W, wb, gw, dcnt, poff, pre, soff, SW, blocks, out):' % Lw,
         '    for j in prange(blocks.size):',
         '        b = blocks[j]',
         '        lo = b * BR',
         '        hi = min(lo + BR, N)',
         '        loc = _e19s_dict(dw, W, wb, gw, pre, soff, SW, b, np.int64(dcnt[b]) - 1).astype(np.uint32)',
         '        w0 = poff[b]',
         '        ng = (hi - lo) // 64',
         '        for g in range(ng):',
         '            a = w0 + g * %d' % Lw,
         '            q = lo + g * 64']
    for j in range(Lw):
        L.append('            x%d = pw[a + %d]' % (j, j))
    for k in range(64):
        bit = k * Lw; wi = bit >> 6; sh = bit & 63
        if sh + Lw <= 64:
            e = '(x%d >> U(%d)) & U(%d)' % (wi, sh, M)
        else:
            e = '((x%d >> U(%d)) | (x%d << U(%d))) & U(%d)' % (wi, sh, wi + 1, 64 - sh, M)
        L.append('            out[q + %d] = loc[np.int64(%s)]' % (k, e))
    L += ['        pos = (w0 + ng * %d) * 64' % Lw,
          '        for i in range(lo + ng * 64, hi):                 # the last block\'s tail',
          '            out[i] = loc[_e19_get(pw, pos, %d)]' % Lw,
          '            pos += %d' % Lw]
    return L


if __name__ == '__main__':
    out = [HEAD]
    for B in range(1, 33): out += bp0(B)
    for B in range(1, 17): out += bp10(B)
    for Lw in range(1, 17): out += e19s(Lw)
    out += ['', '',
            'BP0 = {%s}' % ', '.join('%d: bp0_%d' % (B, B) for B in range(1, 33)),
            'BP10 = {%s}' % ', '.join('%d: bp10_%d' % (B, B) for B in range(1, 17)),
            'E19S = {%s}' % ', '.join('%d: e19s_%d' % (L, L) for L in range(1, 17)), '']
    p = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'wdb_fw.py')
    open(p, 'w', newline='\n').write('\n'.join(out))
    print('wrote', os.path.normpath(p), sum(s.count('\n') + 1 for s in out), 'lines')
